baseURL = "http://blog.jeremylikness.com/"
languageCode = "en-us"
title = "Developer for Life"
theme = "mediumish-gohugo-theme"
summaryLength = 50
copyright = "Jeremy Likness - All Rights Reserved"
disqusShortname = "developerforlife"
googleAnalytics = "UA-1227465-12"
enableEmoji = true

[outputs]
  page = ["HTML", "RSS"]

[params]
    logo = "images/logo.png"
    description = "Code all the things."
    keywords = ["cloud", "webassembly", "azure", "programming", "coding"]

[params.social]
  github = "JeremyLikness"
  linkedin = "JeremyLikness"
  twitter = "JeremyLikness"
  instagram = "JeremyLikness"

[params.index]
  picture = "/images/jumbotron.jpg"
  title = "Developer for Life"
  subtitle = "Code all the things!"
  alertbar = false

[params.author]
  name = "Jeremy Likness"
  thumbnail = "/images/author.png"
  description = "Empowering developers to be their best."

## Main Menu
[[menu.main]]
    name = "ğŸ  Home"
    weight = 50
    identifier = ""
    url = "/"
[[menu.main]]
    name = "ğŸ“ƒ Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "ğŸ“† Upcoming Talks"
    weight = 150
    identifier = "talks"
    url = "/blog/2017-08-17_upcoming-talks/"
[[menu.main]]
    name = "ğŸ—£ Past Presentations"
    weight = 200
    identifier = "presentations"
    url = "/blog/2017-08-17_presentations-archive/"
[[menu.main]]
    name = "â–¶Videos"
    weight = 250
    identifier = "videos"
    url = "https://www.youtube.com/playlist?list=PL1VfiVM16kp-sQ3D3XDLopmScoaOQibFb"
[[menu.main]]
    name = "â„¹ About Me"
    identifier = "about"
    weight = 300
    url = "/static/about"